### ISSUE TITLE
Cert upload

### ISSUE THREAD

**Issue by AvrumFeldman** [hbonath/sonicapi#2]
Hi,

As I see you are also interested in automating SonicWALL devices. I was wondering if you can maybe help me out with implementing one specific API. 

I'm trying to automate uploading new cert-key pairs to the SonicWALL. On [Swaager](https://sonicos-api.sonicwall.com/#/certificates-import-crl/post_certificates_import_crl_ca_name__NAME_) there is inaccurate and partial information on the URI path needed. I figured it out partially from guessing with trial and error but I didn't manage to figure it fully out. I googled around and found this document that does seem to provide more detailed and accurate info https://sonicos-api.sonicwall.com/sonicos_files/6.5.4.7-83n/SOHOW/sonicos_openapi.yml (Search in the file for "cert-key-pair").
I tried implementing it based on the info in the file, but no matter whichever way I submit the FTP or SCP URL I get either a 404 or a 405. 
I tried encoding it with base 64 = 405
I tried URL encoding the FTP URL = 405
I tried providing the FTP URL as is = 404
I tried using the escape sequence I found in the yml file, = the above results.

I'm wondering maybe you can help me out to figure out the correct way to pass the FTP/SCP URL over http (Through SSH it was pretty trivial).

Thanks in advance.

Feel free to close the ticket if you have no interest.

**Comment by hbonath** [comment]
I'll have to try this out. What is your goal here? Are you trying to upload a .PFX file?
Are you using Python or have you tried achieving in curl?

What URL path did you use? This is what I came up with based on Swagger:
https://192.168.168.168/api/sonicos/certificates/import/cert-key-pair/name/mycertificate/password/hunter2/scp/scp\:\/\/sshusername\:sshPassw0rd\@host\/path\/to\/cert.pfx

**Comment by AvrumFeldman** [comment]
> I'll have to try this out. What is your goal here? Are you trying to upload a .PFX file?

Yes trying to upload PFX. Ultimate goal is to automate certificate renewal and upload (but I'm asking on that part as I have that figured out).
> Are you using Python or have you tried achieving in curl?

I tried using curl and got the same results. Thinking of it now, as I'm writing me response I remember I already had escaping issues once on windows. I will try curl on linux and report back.

**Edit**: I can confirm cURL on Linux fails as well.
**Edit2**: I believe I figured it out. I just tested with urlencoding the ftp url **without** the escape sequence and I got back the following response.
```
{
     "status": {
         "success": false

        ,"cli": {
             "mode": "certificate_mode"
            ,"depth": 2
            ,"command": "import cert-key-pair mycertificate password hunter2 ftp ftp://username:password@hostname.com/test.pfx"
            ,"configuring": true
            ,"pending_config": false
            ,"restart_required": "FALSE"
         }

        ,"info": [
             {
                 "level": "error"
                ,"code": "E_ERROR"
                ,"message": "Unable to establish an FTP client connection to 'hostname.com' as user 'username'"
             }
            ,{
                 "level": "error"
                ,"code": "E_ERROR"
                ,"message": "Please verify connectivity and that the FTP username, password and filename are correct."
             }
            ,{
                 "level": "error"
                ,"code": "E_ERROR"
                ,"message": "Could not download file."
             }
         ]
     }
}
```
It seems that indeed PowerShell's escaping caused me this grief the whole time. (until now I was using PowerShell, now I'm testing using native cURL).

> What URL path did you use? This is what I came up with based on Swagger:
https://192.168.168.168/api/sonicos/certificates/import/cert-key-pair/name/mycertificate/password/hunter2/scp/scp\:\/\/sshusername\:sshPassw0rd\@host\/path\/to\/cert.pfx

I tried this exactly this URL structure just using ftp.

**Comment by AvrumFeldman** [comment]
Sorry. I was wrong the whole time. It's not even a PowerShell escaping issue. I was using the wrong HTTP method, POST instead of PUT.

**Note:** No need for the escape characters, only need to URL encode the FTPURL.

Working cURL sample
```
curl -X PUT "https://sonicwall.IP/api/sonicos/certificates/import/cert-key-pair/name/mycertificate/password/passwd/ftp/ftp%3a%2f%2fusername%3apassword%40hostname.com%2ftest.pfx" -k

```
